### ISSUE TITLE
Try to handle all type of scenario where if a user enters wrong id also handle exceptions like if a db connection fails in the middle due to some reason.

### ISSUE THREAD

**Issue by viswajeetlenka9** [PriyaMallick/PythonCRUD-App#1]

**Comment by viswajeetlenka9** [comment]
Whenever you commit for an issue, mention the issue number in the commit message.
For example:
```
git commit -m "Issue #1 : Added exception handlers and validations"
```

**Comment by viswajeetlenka9** [comment]
In current changes, all exception will print the same sentence, so the user might get confused seeing the same message over and over again. Please handle that.
Also you can print the exception that occurs, otherwise the developer will not be able to know where the exception occurs.

**Comment by PriyaMallick** [comment]
Printed the type of exception
